In [1]:
#拿到分析表格之后，需要进行几步操作
f.info()了解数据结构、类型
f.head()/f.tail()前面/最后几行数据
f.describe()

'F:\\峥呈\\python course\\Anaconda_prac'

In [2]:
import pandas as pd

In [3]:
f = pd.read_csv('dataAnalyst1.csv',encoding = 'gbk')
f

,city,companyFullName,companyId,companyLabelList,companyShortName,companySize,businessZones,firstType,secondType,education,industryField,positionId,positionAdvantage,positionName,positionLables,salary,workYear,bottom,top,avg
0,上海,纽海信息技术(上海)有限公司,8581,"['技能培训', '节日礼物', '带薪年假', '岗位晋升']",1号店,2000人,['张江'],技术,数据开发,硕士,移动互联网,2537336,知名平台,数据分析师,"['分析师', '数据分析', '数据挖掘', '数据']",7k-9k,应届毕业生,7,9.0,8.0
1,上海,上海点荣金融信息服务有限责任公司,23177,"['节日礼物', '带薪年假', '岗位晋升', '扁平管理']",点融网,500-2000人,"['五里桥', '打浦桥', '制造局路']",技术,数据开发,本科,金融,2427485,"挑战机会,团队好,与大牛合作,工作环境好",数据分析师-CR2017-SH2909,"['分析师', '数据分析', '数据挖掘', '数据']",10k-15k,应届毕业生,10,15.0,12.5
2,上海,上海晶樵网络信息技术有限公司,57561,"['技能培训', '绩效奖金', '岗位晋升', '管理规范']",SPD,50-150人,['打浦桥'],设计,数据分析,本科,移动互联网,2511252,"时间自由,领导nic",数据分析师,"['分析师', '数据分析', '数据']",4k-6k,应届毕业生,4,6.0,5.0
3,上海,杭州数云信息技术有限公司上海分公司,7502,"['绩效奖金', '股票期权', '五险一金', '通讯津贴']",数云,150-500人,"['龙华', '上海体育场', '万体馆']",市场与销售,数据分析,本科,"企业服务,数据服务",2427530,五险一金 绩效奖金 带薪年假 节日福利,大数据业务分析师【数云校招】,"['商业', '分析师', '大数据', '数据']",6k-8k,应届毕业生,6,8.0,7.0
4,上海,上海银基富力信息技术有限公司,130876,"['年底双薪', '通讯津贴', '定期体检', '绩效奖金']",银基富力,15-50人,"['上海影城', '新华路', '虹桥']",技术,软件开发,本科,其他,2245819,在大牛下指导,BI开发/数据分析师,"['分析师', '数据分析', '数据', 'BI']",2k-3k,应届毕业生,2,3.0,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6871,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,市场/商务/销售类,销售,大专,金融、教育,2469682,高薪双休五险一金时间自由朝九晚五,金融证券分析师&nbsp;&nbsp;助理,"['分析师', '金融', '证券']",10K-20K,不限,10,20.0,15.0
6872,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,产品/需求/项目类,项目管理,大专,金融、教育,2469686,高薪五险一金双休朝九晚五带薪年假20天,金融证券分析师&nbsp;可培训,"['项目管理', '专员', '助理', '实习生', '风控', '采购', '分析师',...",15K-30K,不限,15,30.0,22.5
6873,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,其他,房地产|建筑业,大专,金融、教育,2470949,高薪五险一金双休朝九晚五无加班可培训,金融证券分析师&nbsp;讲师&nbsp;助理,"['分析师', '职业培训', '教育', '培训', '金融', '证券', '股票', ...",15K-30K,不限,15,30.0,22.5
6874,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,市场/商务/销售类,销售,大专,金融、教育,2465839,高薪&nbsp;无加班&nbsp;&nbsp;双休&nbsp;&nbsp;五险一金&nbsp;,金融证券分析师助理讲师助理,"['实习生', '主管', '经理', '顾问', '销售', '客户代表', '分析师',...",10K-20K,不限,10,20.0,15.0
6875,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,金融类,风控,不限,金融、教育,2471674,挑战高薪，挑战自我,1W五险双休诚聘金融分析师助理可兼职,"['分析师', '金融']",8K-15K,不限,8,15.0,11.5

In [4]:
f.avg.sort_values()
f.sort_values(by = 'bottom',ascending = True)
f.sort_values(by = ['bottom','city'],ascending = True)

,city,companyFullName,companyId,companyLabelList,companyShortName,companySize,businessZones,firstType,secondType,education,industryField,positionId,positionAdvantage,positionName,positionLables,salary,workYear,bottom,top,avg
857,上海,上海派兰数据科技有限公司,112100,"['带薪年假', '午餐补助', '领导好', '扁平管理']",派兰数据,少于15人,"['交通大学', '虹桥', '徐家汇']",技术,后端开发,硕士,"数据服务,医疗健康",1400917,福利好 带薪年假 弹性工作 高能TEAM,数据分析师,"['分析师', '数据分析', '数据']",1k-2k,不限,1,2.0,1.5
915,上海,上海瓜牛餐饮管理有限公司,119213,NaN,瓜牛,15-50人,NaN,运营,运营,不限,"O2O,生活服务",2409705,办公环境佳,数据统计,['数据'],1k-2k,不限,1,2.0,1.5
925,上海,VIKI PRIVATE LIMITED,53011,"['美女多', '领导好', '视频网站', '新媒体']",viki,50-150人,"['长寿路', '江宁路', '玉佛寺']",市场与销售,市场/营销,本科,"移动互联网,文化娱乐",2526626,"配备苹果电脑,每周3天的午餐,免费零食饮料",商业数据分析,"['数据分析', '数据', 'BI']",1k-2k,不限,1,2.0,1.5
937,上海,上海派兰数据科技有限公司,112100,"['带薪年假', '午餐补助', '领导好', '扁平管理']",派兰数据,少于15人,"['交通大学', '虹桥', '徐家汇']",运营,运营,本科,"数据服务,医疗健康",2459583,"技能提高,专业团队,人性化管理,干货实在",数据平台技术支持实习生,"['平台', '技术支持', '数据']",1k-2k,不限,1,2.0,1.5
941,上海,康塔瑞韬管理咨询（上海）有限公司,125166,"['年底双薪', '带薪年假', '定期体检', '弹性工作']",Kantar Retail,50-150人,"['天目西路', '火车站', '江宁路']",设计,数据分析,本科,数据服务,2339316,氛围好 锻炼人,数据分析实习生,"['数据分析', '数据']",1k-2k,不限,1,2.0,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4689,成都,成都数联铭品科技有限公司,42711,"['带薪年假', '绩效奖金', '扁平管理', '定期体检']",BBD,150-500人,NaN,技术,高端技术职位,本科,"电子商务,数据服务",2324434,带薪年假、扁平管理、发展空间、上市规划,大数据研发总监,"['大数据', '数据']",50k-80k,5-10年,50,80.0,65.0
1376,深圳,华为技术有限公司,3060,"['技能培训', '节日礼物', '股票期权', '绩效奖金']",华为技术有限公司,2000人,NaN,开发/测试/运维类,运维安全,本科,"移动互联网,企业服务",2573388,高薪~期权~,安全数据分析专家,"['专家', '安全', '网络安全', '病毒分析', '数据分析', '数据']",50k-100k,5-10年,50,100.0,75.0
1428,深圳,华为技术有限公司,3060,"['技能培训', '节日礼物', '股票期权', '绩效奖金']",华为技术有限公司,2000人,NaN,技术,后端开发,本科,"移动互联网,企业服务",2505234,大平台+个人发展空间,数据分析,"['数据分析', '数据']",50k,10年,50,NaN,50.0
3496,北京,北京盛世好运投资管理有限公司,144570,NaN,盛世金控,2000人,['朝外'],技术,管理岗,本科,"金融,社交网络",2462755,智慧社区、综合管理,大数据总监,"['大数据', '合伙人', '数据']",60k-80k,10年,60,80.0,70.0
6596,北京,北京盛世好运投资管理有限公司,144570,NaN,盛世金控,2000人,['朝外'],技术,管理岗,本科,"金融,社交网络",2462755,智慧社区、综合管理,大数据总监,"['大数据', '合伙人', '数据']",60k-80k,10年,60,80.0,70.0

In [4]:
#将表格转置
f.T

,0,1,2,3,4,5,6,7,8,9,...,6866,6867,6868,6869,6870,6871,6872,6873,6874,6875
city,上海,上海,上海,上海,上海,上海,上海,上海,上海,上海,...,北京,北京,北京,北京,北京,北京,北京,北京,北京,北京
companyFullName,纽海信息技术(上海)有限公司,上海点荣金融信息服务有限责任公司,上海晶樵网络信息技术有限公司,杭州数云信息技术有限公司上海分公司,上海银基富力信息技术有限公司,上海青之桐投资管理有限公司,上海好体信息科技有限公司,上海安硕信息技术股份有限公司,上海崇杏健康管理咨询有限公司,五五海淘（上海）科技股份有限公司,...,云联世纪（北京）数据服务有限公司,福建省中天地征信有限公司,北京亿盛融华投资管理有限公司,北京亿盛融华投资管理有限公司,北京亿盛融华投资管理有限公司,北京亿盛融华投资管理有限公司,北京亿盛融华投资管理有限公司,北京亿盛融华投资管理有限公司,北京亿盛融华投资管理有限公司,北京亿盛融华投资管理有限公司
companyId,8581,23177,57561,7502,130876,28095,2002,21863,121208,58109,...,146872,138882,151898,151898,151898,151898,151898,151898,151898,151898
companyLabelList,"['技能培训', '节日礼物', '带薪年假', '岗位晋升']","['节日礼物', '带薪年假', '岗位晋升', '扁平管理']","['技能培训', '绩效奖金', '岗位晋升', '管理规范']","['绩效奖金', '股票期权', '五险一金', '通讯津贴']","['年底双薪', '通讯津贴', '定期体检', '绩效奖金']","['美女多', '出国旅游', '不打卡', '带薪年假']","['年底双薪', '股票期权', '扁平管理', '领导好']","['岗位晋升', '顶尖团队', '福利优厚', '股票期权']","['扁平管理', '弹性工作', '岗位晋升', '领导好']","['股票期权', '带薪年假', '绩效奖金', '岗位晋升']",...,"['弹性工作', '节日礼物', '领导好', '五险一金']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
companyShortName,1号店,点融网,SPD,数云,银基富力,青桐资本,足球魔方,安硕信息（amarsoft）,上海崇杏,55海淘,...,云联数据,中天地征信,亿盛资本,亿盛资本,亿盛资本,亿盛资本,亿盛资本,亿盛资本,亿盛资本,亿盛资本
companySize,2000人,500-2000人,50-150人,150-500人,15-50人,50-150人,150-500人,2000人,15-50人,150-500人,...,少于15人,50-150人,150-500人,150-500人,150-500人,150-500人,150-500人,150-500人,150-500人,150-500人
businessZones,['张江'],"['五里桥', '打浦桥', '制造局路']",['打浦桥'],"['龙华', '上海体育场', '万体馆']","['上海影城', '新华路', '虹桥']",NaN,"['龙华', '植物园', '上海南站']","['黄兴公园', '长白新村', '延吉']","['上海电视台', '南京西路', '人民广场']","['漕宝路', '万源城', '东兰路']",...,NaN,"['德胜门', '新街口', '北太平庄']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
firstType,技术,技术,设计,市场与销售,技术,金融类,技术,产品/需求/项目类,技术,技术,...,市场与销售,技术,其它,金融类,市场/商务/销售类,市场/商务/销售类,产品/需求/项目类,其他,市场/商务/销售类,金融类
secondType,数据开发,数据开发,数据分析,数据分析,软件开发,天使投资/VC/PE,后端开发,产品设计/需求分析,后端开发,后端开发,...,销售,后端开发,教育|培训,风控,销售,销售,项目管理,房地产|建筑业,销售,风控
education,硕士,本科,本科,本科,本科,本科,本科,硕士,本科,本科,...,不限,本科,大专,不限,大专,大专,大专,大专,大专,不限
industryField,移动互联网,金融,移动互联网,"企业服务,数据服务",其他,金融,"移动互联网,电子商务",金融,"移动互联网,医疗健康",电子商务,...,"电子商务,移动互联网","移动互联网,数据服务",金融、教育,金融、教育,金融、教育,金融、教育,金融、教育,金融、教育,金融、教育,金融、教育
positionId,2537336,2427485,2511252,2427530,2245819,2580543,1449715,2568628,2416852,1605795,...,2465479,2093199,2466098,2465818,2469665,2469682,2469686,2470949,2465839,2471674
positionAdvantage,知名平台,"挑战机会,团队好,与大牛合作,工作环境好","时间自由,领导nic",五险一金 绩效奖金 带薪年假 节日福利,在大牛下指导,"留用机会,精品投行,优秀团队,氛围轻松",薪资福利待遇好，晋升空间大,健康体检,"扁平管理,上升空间大,领导好,弹性工作",向大牛学习，有留司机会,...,无责底薪+高提成+五险+年底双薪+带薪年假,以解决技术难题为乐趣的工作最有吸引力,薪资高待遇好,这是一个自我追寻的时代来亿盛资本看看吧。,工作自由、法定假日休息,高薪双休五险一金时间自由朝九晚五,高薪五险一金双休朝九晚五带薪年假20天,高薪五险一金双休朝九晚五无加班可培训,高薪&nbsp;无加班&nbsp;&nbsp;双休&nbsp;&nbsp;五险一金&nbsp;,挑战高薪，挑战自我
positionName,数据分析师,数据分析师-CR2017-SH2909,数据分析师,大数据业务分析师【数云校招】,BI开发/数据分析师,助理分析师,数据工程师,数据咨询顾问(2017年毕业),数据处理工程师（实习生）,数据处理实习生,...,数据中心场地销售,爬虫数据-实习生,分析师助理,交易员分析师,外汇分析师,金融证券分析师&nbsp;&nbsp;助理,金融证券分析师&nbsp;可培训,金融证券分析师&nbsp;讲师&nbsp;助理,金融证券分析师助理讲师助理,1W五险双休诚聘金融分析师助理可兼职
positionLables,"['分析师', '数据分析', '数据挖掘', '数据']","['分析师', '数据分析', '数据挖掘', '数据']","['分析师', '数据分析', '数据']","['商业', '分析师', '大数据', '数据']","['分析师', '数据分析', '数据', 'BI']","['实习', '投资', 'FA', '行业研究', '分析师']",['数据'],"['需求分析', '顾问', '咨询', '咨询顾问', '数据']","['后端开发', '数据']",['数据'],...,"['销售', '销售', '数据']","['爬虫', '数据']","['分析师', '数据分析']","['风控', '经理', '行业研究', '分析师']","['分析师', '资金管理']","['分析师', '金融', '证券']","['项目管理', '专员', '助理', '实习生', '风控', '采购', '分析师',...","['分析师', '职业培训', '教育', '培训', '金融', '证券', '股票', ...","['实习生', '主管', '经理', '顾问', '销售', '客户代表', '分析师',...","['分析师', '金融']"
salary,7k-9k,10k-15k,4k-6k,6k-8k,2k-3k,10k-15k,7k-14k,5k-7k,4k-8k,2k-4k,...,3k-6k,3k-6k,8K-16K,5K-10K,8K-10K,10K-20K,15K-30K,15K-30K,10K-20K,8K-15K
workYear,应届毕业生,应届毕业生,应届毕业生,应届毕业生,应届毕业生,应届毕业生,应届毕业生,应届毕业生,应届毕业生,应届毕业生,...,不限,不限,不限,不限,不限,不限,不限,不限,不限,不限
bottom,7,10,4,6,2,10,7,5,4,2,...,3,3,8,5,8,10,15,15,10,8
top,9,15,6,8,3,15,14,7,8,4,...,6,6,16,10,10,20,30,30,20,15
avg,8,12.5,5,7,2.5,12.5,10.5,6,6,3,...,4.5,4.5,12,7.5,9,15,22.5,22.5,15,11.5

In [20]:
#薪资越高，排名越靠前，降序排列,一般method按平均值排名，比如有相同的4个数都在2，则这四个数就是2.5.如果是最大的话，就是这四个数的最后一位排的顺序来算
#first表示不考虑并列的情况
f['rank'] = f.avg.rank(ascending=False, method='min')
f['rank'] = f.avg.rank(ascending=False, method='max')
f['rank'] = f.avg.rank(ascending=False, method='first')
f

,city,companyFullName,companyId,companyLabelList,companyShortName,companySize,businessZones,firstType,secondType,education,...,positionId,positionAdvantage,positionName,positionLables,salary,workYear,bottom,top,avg,rank
0,上海,纽海信息技术(上海)有限公司,8581,"['技能培训', '节日礼物', '带薪年假', '岗位晋升']",1号店,2000人,['张江'],技术,数据开发,硕士,...,2537336,知名平台,数据分析师,"['分析师', '数据分析', '数据挖掘', '数据']",7k-9k,应届毕业生,7,9.0,8.0,5733.0
1,上海,上海点荣金融信息服务有限责任公司,23177,"['节日礼物', '带薪年假', '岗位晋升', '扁平管理']",点融网,500-2000人,"['五里桥', '打浦桥', '制造局路']",技术,数据开发,本科,...,2427485,"挑战机会,团队好,与大牛合作,工作环境好",数据分析师-CR2017-SH2909,"['分析师', '数据分析', '数据挖掘', '数据']",10k-15k,应届毕业生,10,15.0,12.5,4421.0
2,上海,上海晶樵网络信息技术有限公司,57561,"['技能培训', '绩效奖金', '岗位晋升', '管理规范']",SPD,50-150人,['打浦桥'],设计,数据分析,本科,...,2511252,"时间自由,领导nic",数据分析师,"['分析师', '数据分析', '数据']",4k-6k,应届毕业生,4,6.0,5.0,6347.0
3,上海,杭州数云信息技术有限公司上海分公司,7502,"['绩效奖金', '股票期权', '五险一金', '通讯津贴']",数云,150-500人,"['龙华', '上海体育场', '万体馆']",市场与销售,数据分析,本科,...,2427530,五险一金 绩效奖金 带薪年假 节日福利,大数据业务分析师【数云校招】,"['商业', '分析师', '大数据', '数据']",6k-8k,应届毕业生,6,8.0,7.0,6028.0
4,上海,上海银基富力信息技术有限公司,130876,"['年底双薪', '通讯津贴', '定期体检', '绩效奖金']",银基富力,15-50人,"['上海影城', '新华路', '虹桥']",技术,软件开发,本科,...,2245819,在大牛下指导,BI开发/数据分析师,"['分析师', '数据分析', '数据', 'BI']",2k-3k,应届毕业生,2,3.0,2.5,6772.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6871,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,市场/商务/销售类,销售,大专,...,2469682,高薪双休五险一金时间自由朝九晚五,金融证券分析师&nbsp;&nbsp;助理,"['分析师', '金融', '证券']",10K-20K,不限,10,20.0,15.0,4229.0
6872,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,产品/需求/项目类,项目管理,大专,...,2469686,高薪五险一金双休朝九晚五带薪年假20天,金融证券分析师&nbsp;可培训,"['项目管理', '专员', '助理', '实习生', '风控', '采购', '分析师',...",15K-30K,不限,15,30.0,22.5,2249.0
6873,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,其他,房地产|建筑业,大专,...,2470949,高薪五险一金双休朝九晚五无加班可培训,金融证券分析师&nbsp;讲师&nbsp;助理,"['分析师', '职业培训', '教育', '培训', '金融', '证券', '股票', ...",15K-30K,不限,15,30.0,22.5,2250.0
6874,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,市场/商务/销售类,销售,大专,...,2465839,高薪&nbsp;无加班&nbsp;&nbsp;双休&nbsp;&nbsp;五险一金&nbsp;,金融证券分析师助理讲师助理,"['实习生', '主管', '经理', '顾问', '销售', '客户代表', '分析师',...",10K-20K,不限,10,20.0,15.0,4230.0
6875,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,金融类,风控,不限,...,2471674,挑战高薪，挑战自我,1W五险双休诚聘金融分析师助理可兼职,"['分析师', '金融']",8K-15K,不限,8,15.0,11.5,5224.0

In [21]:
f.sort_values(by = 'avg',ascending = False)

,city,companyFullName,companyId,companyLabelList,companyShortName,companySize,businessZones,firstType,secondType,education,...,positionId,positionAdvantage,positionName,positionLables,salary,workYear,bottom,top,avg,rank
1376,深圳,华为技术有限公司,3060,"['技能培训', '节日礼物', '股票期权', '绩效奖金']",华为技术有限公司,2000人,NaN,开发/测试/运维类,运维安全,本科,...,2573388,高薪~期权~,安全数据分析专家,"['专家', '安全', '网络安全', '病毒分析', '数据分析', '数据']",50k-100k,5-10年,50,100.0,75.0,3.0
2865,北京,北京达佳互联信息技术有限公司,1880,"['股票期权', '五险一金', '弹性工作', '定期体检']",快手,50-150人,"['中关村', '北京大学', '苏州街']",开发/测试/运维类,运维安全,本科,...,2538369,"待遇优厚,平台超赞,租房补助,美味午晚餐",高级数据中心架构师,"['架构师', '运维', '数据']",50k-100k,3-5年,50,100.0,75.0,4.0
836,上海,上海友希数码科技发展有限公司,150849,"['年底双薪', '专项奖金', '年终分红', '带薪年假']",友希科技,500-2000人,['张江'],开发/测试/运维类,数据开发,本科,...,2568751,"VR,微鲸科技,阿里腾讯,行业领先",大数据架构师（阿里/腾讯/华人文化共同投资）,"['专家', '架构师', '大数据', '数据']",50k-100k,5-10年,50,100.0,75.0,1.0
844,上海,上海遇志投资管理有限公司,151989,"['年底双薪', '股票期权', '创业氛围', '专项奖金']",复星金服,2000人,['漕河泾'],技术,管理岗,硕士,...,2475927,复兴集团背景 强大资源投入 发挥空间巨大,数据技术总监,"['技术总监', '数据']",50k-100k,5-10年,50,100.0,75.0,2.0
3496,北京,北京盛世好运投资管理有限公司,144570,NaN,盛世金控,2000人,['朝外'],技术,管理岗,本科,...,2462755,智慧社区、综合管理,大数据总监,"['大数据', '合伙人', '数据']",60k-80k,10年,60,80.0,70.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,上海,上海派兰数据科技有限公司,112100,"['带薪年假', '午餐补助', '领导好', '扁平管理']",派兰数据,少于15人,"['交通大学', '虹桥', '徐家汇']",运营,运营,本科,...,2459583,"技能提高,专业团队,人性化管理,干货实在",数据平台技术支持实习生,"['平台', '技术支持', '数据']",1k-2k,不限,1,2.0,1.5,6856.0
925,上海,VIKI PRIVATE LIMITED,53011,"['美女多', '领导好', '视频网站', '新媒体']",viki,50-150人,"['长寿路', '江宁路', '玉佛寺']",市场与销售,市场/营销,本科,...,2526626,"配备苹果电脑,每周3天的午餐,免费零食饮料",商业数据分析,"['数据分析', '数据', 'BI']",1k-2k,不限,1,2.0,1.5,6855.0
915,上海,上海瓜牛餐饮管理有限公司,119213,NaN,瓜牛,15-50人,NaN,运营,运营,不限,...,2409705,办公环境佳,数据统计,['数据'],1k-2k,不限,1,2.0,1.5,6854.0
6755,北京,百度在线网络技术（北京）有限公司,1575,"['股票期权', '弹性工作', '五险一金', '免费班车']",百度,2000人,"['西北旺', '马连洼']",市场与销售,市场/营销,不限,...,2505127,研究课题丰富，边工作边学习,【实习】数据分析实习生,"['数据分析', '数据']",1k-2k,不限,1,2.0,1.5,6875.0
4737,南京,南京新视云网络科技有限公司,61623,"['技能培训', '年底双薪', '带薪年假', '扁平管理']",司法云平台,50-150人,"['安德门', '铁心桥']",市场与销售,数据分析,本科,...,2562974,餐补车补,数据分析,"['商业', '数据分析', '数据']",1k-2k,1年,1,2.0,1.5,6872.0

In [27]:
#重复值，重复值计算
f.info()
f.city.unique()
f.city.value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6876 entries, 0 to 6875
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   city               6876 non-null   object
 1   companyFullName    6876 non-null   object
 2   companyId          6876 non-null   int64
 3   companyLabelList   6170 non-null   object
 4   companyShortName   6876 non-null   object
 5   companySize        6876 non-null   object
 6   businessZones      4873 non-null   object
 7   firstType          6869 non-null   object
 8   secondType         6870 non-null   object
 9   education          6876 non-null   object
 10  industryField      6876 non-null   object
 11  positionId         6876 non-null   int64
 12  positionAdvantage  6876 non-null   object
 13  positionName       6876 non-null   object
 14  positionLables     6844 non-null   object
 15  salary             6876 non-null   object
 16  workYear           6876 non-null   object
 17  bottom             6876 non-null   int64
 18  top                6823 non-null   float64
 19  avg                6876 non-null   float64
 20  rank               6876 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.1+ MB

北京    4177
上海     980
深圳     527
杭州     407
广州     335
成都     135
南京      83
武汉      69
西安      51
苏州      37
厦门      30
长沙      25
天津      20
Name: city, dtype: int64

In [32]:
#常见的数据分析维度
f.describe()
f.avg.describe()
f.sum()
f.mean()
f.median()

companyId       46668.0
positionId    2352735.5
bottom             12.0
top                20.0
avg                16.0
rank             3438.5
dtype: float64

In [34]:
#累计的计算
f['cumsum'] = f.avg.cumsum()
f

,city,companyFullName,companyId,companyLabelList,companyShortName,companySize,businessZones,firstType,secondType,education,...,positionAdvantage,positionName,positionLables,salary,workYear,bottom,top,avg,rank,cumsum
0,上海,纽海信息技术(上海)有限公司,8581,"['技能培训', '节日礼物', '带薪年假', '岗位晋升']",1号店,2000人,['张江'],技术,数据开发,硕士,...,知名平台,数据分析师,"['分析师', '数据分析', '数据挖掘', '数据']",7k-9k,应届毕业生,7,9.0,8.0,5733.0,8.0
1,上海,上海点荣金融信息服务有限责任公司,23177,"['节日礼物', '带薪年假', '岗位晋升', '扁平管理']",点融网,500-2000人,"['五里桥', '打浦桥', '制造局路']",技术,数据开发,本科,...,"挑战机会,团队好,与大牛合作,工作环境好",数据分析师-CR2017-SH2909,"['分析师', '数据分析', '数据挖掘', '数据']",10k-15k,应届毕业生,10,15.0,12.5,4421.0,20.5
2,上海,上海晶樵网络信息技术有限公司,57561,"['技能培训', '绩效奖金', '岗位晋升', '管理规范']",SPD,50-150人,['打浦桥'],设计,数据分析,本科,...,"时间自由,领导nic",数据分析师,"['分析师', '数据分析', '数据']",4k-6k,应届毕业生,4,6.0,5.0,6347.0,25.5
3,上海,杭州数云信息技术有限公司上海分公司,7502,"['绩效奖金', '股票期权', '五险一金', '通讯津贴']",数云,150-500人,"['龙华', '上海体育场', '万体馆']",市场与销售,数据分析,本科,...,五险一金 绩效奖金 带薪年假 节日福利,大数据业务分析师【数云校招】,"['商业', '分析师', '大数据', '数据']",6k-8k,应届毕业生,6,8.0,7.0,6028.0,32.5
4,上海,上海银基富力信息技术有限公司,130876,"['年底双薪', '通讯津贴', '定期体检', '绩效奖金']",银基富力,15-50人,"['上海影城', '新华路', '虹桥']",技术,软件开发,本科,...,在大牛下指导,BI开发/数据分析师,"['分析师', '数据分析', '数据', 'BI']",2k-3k,应届毕业生,2,3.0,2.5,6772.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6871,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,市场/商务/销售类,销售,大专,...,高薪双休五险一金时间自由朝九晚五,金融证券分析师&nbsp;&nbsp;助理,"['分析师', '金融', '证券']",10K-20K,不限,10,20.0,15.0,4229.0,119944.0
6872,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,产品/需求/项目类,项目管理,大专,...,高薪五险一金双休朝九晚五带薪年假20天,金融证券分析师&nbsp;可培训,"['项目管理', '专员', '助理', '实习生', '风控', '采购', '分析师',...",15K-30K,不限,15,30.0,22.5,2249.0,119966.5
6873,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,其他,房地产|建筑业,大专,...,高薪五险一金双休朝九晚五无加班可培训,金融证券分析师&nbsp;讲师&nbsp;助理,"['分析师', '职业培训', '教育', '培训', '金融', '证券', '股票', ...",15K-30K,不限,15,30.0,22.5,2250.0,119989.0
6874,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,市场/商务/销售类,销售,大专,...,高薪&nbsp;无加班&nbsp;&nbsp;双休&nbsp;&nbsp;五险一金&nbsp;,金融证券分析师助理讲师助理,"['实习生', '主管', '经理', '顾问', '销售', '客户代表', '分析师',...",10K-20K,不限,10,20.0,15.0,4230.0,120004.0
6875,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,金融类,风控,不限,...,挑战高薪，挑战自我,1W五险双休诚聘金融分析师助理可兼职,"['分析师', '金融']",8K-15K,不限,8,15.0,11.5,5224.0,120015.5

In [45]:
#分层,分组函数，分层函数,bins是分成几组，labels是分组的名称
f['bins'] = pd.cut(f.avg, bins = 5,labels=list('abcde'))
f

,city,companyFullName,companyId,companyLabelList,companyShortName,companySize,businessZones,firstType,secondType,education,...,positionName,positionLables,salary,workYear,bottom,top,avg,rank,cumsum,bins
0,上海,纽海信息技术(上海)有限公司,8581,"['技能培训', '节日礼物', '带薪年假', '岗位晋升']",1号店,2000人,['张江'],技术,数据开发,硕士,...,数据分析师,"['分析师', '数据分析', '数据挖掘', '数据']",7k-9k,应届毕业生,7,9.0,8.0,5733.0,8.0,a
1,上海,上海点荣金融信息服务有限责任公司,23177,"['节日礼物', '带薪年假', '岗位晋升', '扁平管理']",点融网,500-2000人,"['五里桥', '打浦桥', '制造局路']",技术,数据开发,本科,...,数据分析师-CR2017-SH2909,"['分析师', '数据分析', '数据挖掘', '数据']",10k-15k,应届毕业生,10,15.0,12.5,4421.0,20.5,a
2,上海,上海晶樵网络信息技术有限公司,57561,"['技能培训', '绩效奖金', '岗位晋升', '管理规范']",SPD,50-150人,['打浦桥'],设计,数据分析,本科,...,数据分析师,"['分析师', '数据分析', '数据']",4k-6k,应届毕业生,4,6.0,5.0,6347.0,25.5,a
3,上海,杭州数云信息技术有限公司上海分公司,7502,"['绩效奖金', '股票期权', '五险一金', '通讯津贴']",数云,150-500人,"['龙华', '上海体育场', '万体馆']",市场与销售,数据分析,本科,...,大数据业务分析师【数云校招】,"['商业', '分析师', '大数据', '数据']",6k-8k,应届毕业生,6,8.0,7.0,6028.0,32.5,a
4,上海,上海银基富力信息技术有限公司,130876,"['年底双薪', '通讯津贴', '定期体检', '绩效奖金']",银基富力,15-50人,"['上海影城', '新华路', '虹桥']",技术,软件开发,本科,...,BI开发/数据分析师,"['分析师', '数据分析', '数据', 'BI']",2k-3k,应届毕业生,2,3.0,2.5,6772.0,35.0,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6871,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,市场/商务/销售类,销售,大专,...,金融证券分析师&nbsp;&nbsp;助理,"['分析师', '金融', '证券']",10K-20K,不限,10,20.0,15.0,4229.0,119944.0,a
6872,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,产品/需求/项目类,项目管理,大专,...,金融证券分析师&nbsp;可培训,"['项目管理', '专员', '助理', '实习生', '风控', '采购', '分析师',...",15K-30K,不限,15,30.0,22.5,2249.0,119966.5,b
6873,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,其他,房地产|建筑业,大专,...,金融证券分析师&nbsp;讲师&nbsp;助理,"['分析师', '职业培训', '教育', '培训', '金融', '证券', '股票', ...",15K-30K,不限,15,30.0,22.5,2250.0,119989.0,b
6874,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,市场/商务/销售类,销售,大专,...,金融证券分析师助理讲师助理,"['实习生', '主管', '经理', '顾问', '销售', '客户代表', '分析师',...",10K-20K,不限,10,20.0,15.0,4230.0,120004.0,a
6875,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,金融类,风控,不限,...,1W五险双休诚聘金融分析师助理可兼职,"['分析师', '金融']",8K-15K,不限,8,15.0,11.5,5224.0,120015.5,a

In [7]:
f['bins'] = pd.cut(f.avg, bins = [0,10,20,30,100],labels=('0-10','10-20','20-30','30-100'))
f.query('avg >15')

,city,companyFullName,companyId,companyLabelList,companyShortName,companySize,businessZones,firstType,secondType,education,...,positionId,positionAdvantage,positionName,positionLables,salary,workYear,bottom,top,avg,bins
38,上海,上海好居信息科技有限公司,30533,"['股票期权', '岗位晋升', '扁平管理', '补充商业保险']",悟空找房,500-2000人,"['交通大学', '虹桥', '徐家汇']",设计,数据分析,本科,...,2459208,弹性工作、五险一金、大牛如云,大数据分析师,"['分析师', '大数据', '数据分析', '数据']",15k-25k,1-3年,15,25.0,20.0,10-20
50,上海,浙江每日互动网络科技股份有限公司,13163,"['绩效奖金', '股票期权', '年底双薪', '专项奖金']",个推,150-500人,NaN,设计,用户研究,本科,...,2551555,带薪年假 五险一金 生日Party 餐补,数据分析师,"['分析师', '数据分析', '数据']",15k-25k,1-3年,15,25.0,20.0,10-20
54,上海,上海凌融网络科技有限公司,54000,"['年底双薪', '节日礼物', '技能培训', '股票期权']",口袋理财,150-500人,"['五角场', '大学区', '长海医院']",技术,数据开发,本科,...,2439826,"好吃,好喝,好玩,好多美女",数据分析师,"['分析师', '数据分析', '数据挖掘', '数据']",15k-30k,1-3年,15,30.0,22.5,20-30
63,上海,万达信息科技有限公司,27061,"['专项奖金', '五险一金', '带薪年假', '午餐补助']",万达电商,2000人,"['世纪公园', '花木', '塘桥']",技术,后端开发,本科,...,2536576,"免费三餐,大平台",数据分析师,"['分析师', '数据分析', '后端开发', '数据']",15k-25k,1-3年,15,25.0,20.0,10-20
68,上海,杭州财米科技有限公司,4448,"['年底多薪', '岗位晋升', '定期体检', '五险一金']",挖财,500-2000人,"['世纪公园', '花木', '塘桥']",市场与销售,市场/营销,本科,...,591162,"期权激励,带薪年假,弹性工作,年底多薪",高级数据分析师,"['分析师', '数据分析', '数据']",12k-24k,1-3年,12,24.0,18.0,10-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6838,北京,海航生态科技集团有限公司,101076,"['节日礼物', '年底双薪', '折扣机票', '带薪年假']",海航生态科技,500-2000人,"['和平里', '雍和宫', '安定门']",运营,运营,本科,...,2341750,"500强,年终多薪",数据分析主管,"['数据分析', '数据']",12k-24k,不限,12,24.0,18.0,10-20
6853,北京,中金金融认证中心有限公司,31317,"['年底双薪', '绩效奖金', '管理规范', '定期体检']",中国金融认证中心,500-2000人,"['菜市口', '陶然亭', '白纸坊']",技术,高端技术职位,本科,...,1867911,银行大数据风控分析，海量交易数据实操,大数据开发工程师,"['大数据', '数据库', '数据']",15k-30k,不限,15,30.0,22.5,20-30
6865,北京,佰润明辉（北京）投资有限公司,121899,NaN,佰润明辉,150-500人,"['团结湖', '朝阳公园', '三里屯', '团结湖', '朝阳公园', '三里屯']",金融,投融资,不限,...,1702627,五险一金 年终奖 领导nice 发展空间大,金融二级市场证券分析师／交易员／操盘手 零基础带薪培训,"['分析师', '金融', '证券']",15k-30k,不限,15,30.0,22.5,20-30
6872,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,产品/需求/项目类,项目管理,大专,...,2469686,高薪五险一金双休朝九晚五带薪年假20天,金融证券分析师&nbsp;可培训,"['项目管理', '专员', '助理', '实习生', '风控', '采购', '分析师',...",15K-30K,不限,15,30.0,22.5,20-30
6873,北京,北京亿盛融华投资管理有限公司,151898,NaN,亿盛资本,150-500人,NaN,其他,房地产|建筑业,大专,...,2470949,高薪五险一金双休朝九晚五无加班可培训,金融证券分析师&nbsp;讲师&nbsp;助理,"['分析师', '职业培训', '教育', '培训', '金融', '证券', '股票', ...",15K-30K,不限,15,30.0,22.5,20-30

In [69]:
#用for循环获取分组后的明细,算出每个城市薪资的最大值和最小值
f.groupby(by = ['city','workYear'])
for k,v in f.groupby(by = ['city']):
    print(k)
    print(v.avg.max()-v.avg.min())
    print(max(v.avg)-min(v.avg))

上海
73.5
北京
73.5
南京
23.5
厦门
21.5
天津
14.5
广州
43.5
成都
63.5
杭州
57.5
武汉
25.0
深圳
73.5
苏州
26.0
西安
32.5
长沙
12.5

In [74]:
f2 = pd.read_csv('company_sql.csv',encoding='gbk')
f2

,companyId,companyFullName,companyLabelList,companyShortName,companySize,businessZones
0,8581,纽海信息技术(上海)有限公司,"['技能培训', '节日礼物', '带薪年假', '岗位晋升']",1号店,2000人以上,['张江']
1,23177,上海点荣金融信息服务有限责任公司,"['节日礼物', '带薪年假', '岗位晋升', '扁平管理']",点融网,500-2000人,"['五里桥', '打浦桥', '制造局路']"
2,57561,上海晶樵网络信息技术有限公司,"['技能培训', '绩效奖金', '岗位晋升', '管理规范']",SPD,50-150人,['打浦桥']
3,7502,杭州数云信息技术有限公司上海分公司,"['绩效奖金', '股票期权', '五险一金', '通讯津贴']",数云,150-500人,"['龙华', '上海体育场', '万体馆']"
4,130876,上海银基富力信息技术有限公司,"['年底双薪', '通讯津贴', '定期体检', '绩效奖金']",银基富力,15-50人,"['上海影城', '新华路', '虹桥']"
...,...,...,...,...,...,...
2291,112379,天津美源星商贸有限公司,"['年底双薪', '绩效奖金', '年终分红', '午餐补助']",天津美源星,150-500人,NaN
2292,32877,北京瑞达恒建筑咨询股份有限公司,"['技能培训', '年底双薪', '带薪年假', '绩效奖金']",瑞达恒RCC,500-2000人,['尖山']
2293,52887,天津小猫网络科技有限公司,"['技能培训', '股票期权', '绩效奖金', '扁平管理']",天津小猫,15-50人,"['和平路', '火车站', '后广场']"
2294,59239,普信资产管理有限公司,"['节日礼物', '技能培训', '绩效奖金', '岗位晋升']",龙宝斋财富,2000人以上,['京广桥']
2295,156832,北京富通基业投资有限公司,"['节日礼物', '美女多', '帅哥多', '技能培训']",北京富通基业投资有限公司,50-150人,['西二旗']